### ISSUE TITLE
Add docker-compose to run nhost locally

### ISSUE THREAD

**Issue by ctwhome** [MarcelloTheArcane/nhost-template#7]
what about a docker-compose configuration to run nhost locally. How does it sound?

**Comment by MarcelloTheArcane** [comment]
Hello @ctwhome!

That sounds more appropriate to the Nhost repository - in fact it looks like that already exists: https://github.com/nhost/hasura-backend-plus/blob/master/docker-compose.yaml

This is just a frontend template on Nuxt for integrating with Nhost, rather than actually running Nhost.

**Comment by ctwhome** [comment]
Yes, I agree. I think your code could be the perfect starting point for the nhost nuxt example https://github.com/nhost/nhost-nuxtjs-example-app

thank you for your work @MarcelloTheArcane  btw!
